import fs from "node:fs";
import path from "node:path";
import readline from "node:readline/promises";
import { hashPassword, randomHex } from "./crypto.js";

/**
 * Writes .env with fresh secrets. Run once.
 * Regenerating MASTER_KEY makes every existing encrypted row unreadable.
 * there is no recovery path, by design.
 */
async function main() {
  const envPath = path.resolve(".env");
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  if (fs.existsSync(envPath)) {
    const answer = await rl.question(".env already exists. Overwrite and lose access to existing data? (yes/no) ");
    if (answer.trim().toLowerCase() !== "yes") {
      console.log("Left alone.");
      rl.close();
      return;
    }
  }

  const password = await rl.question("Choose a password: ");
  if (password.length < 10) {
    console.log("\nToo short. Use at least 10 characters.");
    rl.close();
    process.exit(1);
  }
  const apiKey = await rl.question("Ollama API key (from ollama.com/settings/keys, blank to add later): ");
  rl.close();

  const env = `# Generated by npm run init on ${new Date().toISOString()}
# MASTER_KEY decrypts everything. Lose it and the data is gone. Back it up somewhere safe.
MASTER_KEY=${randomHex(32)}
SESSION_SECRET=${randomHex(32)}
PASSWORD_HASH=${hashPassword(password)}

OLLAMA_API_KEY=${apiKey.trim()}
OLLAMA_HOST=https://ollama.com
OLLAMA_MODEL=gpt-oss:120b

# Embedded Postgres by default. Set DATABASE_URL to move to a server.
DATA_DIR=./data
# DATABASE_URL=postgres://user:pass@host:5432/ledger

EXPORT_DIR=./export
OWNER_NAME=you
PORT=4321
BIND_HOST=127.0.0.1
`;

  fs.writeFileSync(envPath, env, { mode: 0o600 });
  console.log(`\nWrote ${envPath} (permissions 600).`);
  console.log("Back up MASTER_KEY now. It is the only way to read your data.\n");
}

main();
